name: CI

on:
  push:
    branches: [ main ]
  pull_request:

env:
  SCARB_VERSION: 2.8.5

jobs:
  check:
    name: Check Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Scarb
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh -s -- -v $SCARB_VERSION
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install Starknet Foundry
        run: |
          curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | sh
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Check format
        run: scarb fmt --check


  test:
    runs-on: ubuntu-latest
    name: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.8.5"

      - name: Set up snforge
        uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.33.0"

      - name: Run tests
        run: snforge test
